pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/Teja2803/Final_upgrad.git'
        GIT_BRANCH = 'main'
        AWS_SERVER = 'ubuntu@18.209.104.46'
        AZURE_SERVER = 'azureuser@52.224.56.69'
        AZURE_PASSWORD = credentials('azure-ssh-password-id')
    }

    stages {
        stage('Checkout HTML Files') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }
        stage('Deploy to AWS') {
            steps {
                sshagent(['aws-ssh-key-credentials-id']) {
                    sh """
                        scp -o StrictHostKeyChecking=no Task4/files/index-aws.html ${AWS_SERVER}:/tmp/index-aws.html
                        ssh -o StrictHostKeyChecking=no ${AWS_SERVER} 'sudo mv /tmp/index-aws.html /var/www/html/index.html && sudo systemctl restart nginx'
                    """
                }
            }
        }
        stage('Deploy to Azure') {
            steps {
                sshagent(['azure-id']) {
                sh '''
                    scp -o StrictHostKeyChecking=no Task4/files/index-azure.html ubuntu@52.224.56.69:/tmp/index-azure.html
                    ssh -o StrictHostKeyChecking=no ubuntu@52.224.56.69 'sudo mv /tmp/index-azure.html /var/www/html/index.html && sudo systemctl restart nginx'
                '''
                }
            }
        }
    }
}
