[aws_app_machine]
ec2-app ansible_host=18.209.104.46 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/bastion.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[azure_vm]
azure-vm ansible_host=74.235.6.187 ansible_user=azureuser ansible_password=Password1234! ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers:children]
aws_app_machine
azure_vm
